# Lorsque je push sur ma branche features
# Je veux que mon container se crée
# Je veux que le code dans ce container soit executé
# Je veux savoir si ce code a été correctement executé, et voir le resultat si possible
# Je veux testé si des failles de sécurité existe dans : 
#   - mon Dockerfile, 
#   - mon container, 
#   - mon appli python

# Si tout cela est OK, alors je veux :
# - pull request sur main, mais me laisser merge manuellement (check humain)
# - push mon app sur le docker hub

# Plus tard, je voudrais déployer sur AWS (je n'ai pas encore le compte associé)


name: DevSecOps Training

on:
  push:
    branches:
      - features

jobs: 
  build:
    #container: python:3.13.7-alpine
    runs-on: ubuntu-latest
    steps:

        #Checkout (DL du code)
      - name: Checkout du Repo
        uses: actions/checkout@v3

        #Scan Code Source
      - name: Scan SAST
        uses: returntocorp/semgrep-action@v1

        #Build
      - name: Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/daily-cats-facts:1.0 .

        #Scan Container
      - name: Scan Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/daily-cats-facts:1.0

        #Dockerhub
      - name: Connexion au Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        #Push
      - name: Push sur Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/daily-cats-facts:1.0

  
  test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
        #Dockerhub
      - name: Connexion au Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        #Pull
      - name: Pull Daily Cats facts
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/daily-cats-facts:1.0

        #Test
      - name: Test de l'app
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/daily-cats-facts:1.0

